src/RBod.PlayBall.GroupManagement.Web/Models/GroupViewmodel.cs
namespace RBod.PlayBall.GroupManagement.Web.Models
{
    public class GroupViewModel
    {
        public long Id { get; set; }

        public string Name { get; set; }
    }
}

src/RBod.PlayBall.GroupManagement.Web/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using RBod.PlayBall.GroupManagement.Business.Services;
using RBod.PlayBall.GroupManagement.Web.Mappings;
using RBod.PlayBall.GroupManagement.Web.Models;

namespace RBod.PlayBall.GroupManagement.Web.Controllers
{
    [Route("groups")]
    public class GroupsController : Controller
    {
        private readonly IGroupsService groupService;

        public GroupsController( IGroupsService groupService)
        {
            this.groupService = groupService;
        }
        
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View(this.groupService.Get().ToViewModels());
        }

        [HttpGet]
        [Route("{id}")]
        public IActionResult Details(long id)
        {
            var group = this.groupService.GetById(id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group.ToViewModel());
        }

        [HttpPost]
        [Route("{id}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, GroupViewModel model)
        {
            var group = this.groupService.Update(model.ToServiceModel());
            if (group == null)
            {
                return NotFound();
            }
            
            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("CreatePost")]
        public IActionResult Create(GroupViewModel model)
        {
            this.groupService.Add(model.ToServiceModel());
            return RedirectToAction(nameof(this.Index));
        }
    }
}

src/RBod.PlayBall.GroupManagement.Web/Views/Groups/Create.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="CreatePost" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" />
    <button type="submit">Save</button>
</form>

src/RBod.PlayBall.GroupManagement.Web/Views/Groups/Details.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="Edit" asp-route-id="@Model.Id" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name"/>
    <button type="submit">Save</button>
</form>

@Model.Name

src/RBod.PlayBall.GroupManagement.Web/Views/Groups/Index.cshtml
@model IEnumerable<GroupViewModel>

<ul>
    @foreach (var group in Model)
    {
        <li>@group.Name <a asp-controller="Groups" asp-action="Details" asp-route-id="@group.Id">Edit</a></li>
    }
</ul>

<a asp-controller="Groups" asp-action="Create">Create</a>